# Start from the official Go image
FROM golang:1.20-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY *.go ./

RUN go build -o main main.go

FROM alpine:latest

WORKDIR /app

COPY --from=builder /app/main ./

EXPOSE 8080

CMD ["./main"]