version: '3.9'

services:
  frontend:
    build:
      context: ./frontend
    environment:
      - REACT_APP_API_URL=http://backend:8080/api
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-net
      
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
